server:
  port: 8861

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8869/eureka/

# 按照官方文档的指示，需要改变etc/hosts，linux系统通过vim /etc/hosts ,加上：
# 127.0.0.1 peer1
# 127.0.0.1 peer2
# windows电脑，在c:/windows/systems/drivers/etc/hosts 修改.加上面ip