
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8887
  tomcat:
    max-http-header-size: 3145728

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vellerzheng/mbootcloud
          search-paths: respo
          username: ********
          password: ********
      label: master
