
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  #application.yml文件只能是8888端口，用bootstrap.properties文件，可以配置其他端口
  port: 8888
  tomcat:
    max-http-header-size: 3145728

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/vellerzheng/mbootcloud
          search-paths: conf_file_center
          username: *******
          password: *******

